# Generated by Django 4.2.1 on 2023-05-31 06:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_champ', models.CharField(max_length=100)),
                ('name_team', models.CharField(max_length=100)),
                ('tours', models.IntegerField(help_text='Тур должны быть в диапазоне (1 to 50)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('points', models.IntegerField(help_text='Очки должны быть в диапазоне (0 to 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('games', models.IntegerField(help_text='Игры должны быть в диапазоне (0 to 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('loses', models.IntegerField(help_text='Поражения должны быть в диапазоне (0 to 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('wins', models.IntegerField(help_text='Победы должны быть в диапазоне (0 to 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('draw', models.IntegerField(help_text='Ничья должны быть в диапазоне (0 to 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('logo', models.ImageField(upload_to='')),
                ('goals_scored', models.IntegerField(help_text='Забитые мячи должны быть в диапазоне (0 to 200)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('goals_missed', models.IntegerField(help_text='Пропущенные мячи должны быть в диапазоне (0 to 200)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champ_table', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', '-goals_scored', 'goals_missed'],
                'indexes': [models.Index(fields=['-points'], name='table_table_points_0b6865_idx')],
            },
        ),
    ]
