# Generated by Django 4.2.1 on 2023-05-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='table',
            name='table_table_points_0b6865_idx',
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['-points', 'name_champ'], name='table_table_points_6e1b5d_idx'),
        ),
    ]
