# Generated by Django 4.2.1 on 2023-05-31 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_remove_table_table_table_points_0b6865_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_champ', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('num_tours', models.IntegerField(help_text='Тур должны быть в диапазоне (1 to 50)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
            ],
        ),
    ]
