# Generated by Django 4.2.1 on 2023-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_champ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champ',
            name='name_champ',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
