# Generated by Django 4.2.1 on 2023-06-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_champ_name_champ'),
    ]

    operations = [
        migrations.AddField(
            model_name='champ',
            name='slug',
            field=models.CharField(default='rpl', max_length=5),
        ),
    ]
