# Generated by Django 4.2.1 on 2023-06-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_champ_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champ',
            name='slug',
            field=models.CharField(default='rpl', max_length=20),
        ),
    ]
